version: '3.7'
services:

  webapp:
    image: savantly/sprout-webapp
    container_name: sprout-superset-webapp
    restart: always
    ports:
      - 3000:3000
    environment: 
      - SPROUT_API_URL=http://host.docker.internal:8080

  db:
    image: postgres
    container_name: sprout-superset-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=sprout
      - POSTGRES_PASSWORD=sprout
      - POSTGRES_USER=sprout

