sprout:
  jpa:
    packages-to-scan:
    - net.savantly.sprout.server.domain
  security:
    authentication:
      basic:
        users:
        - username: admin
          password: changeme!
          email-address: example@savantly.net
          roles: ADMIN
    authorization:
      patterns:
      - path: /api/plugins**
        expression:
          GET: permitAll
      - path: /api/dashboards/**
        expression:
          GET: permitAll

spring:
  banner:
    location: banner.txt
  mvc:
    log-request-details: true
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: local
  data:
    rest:
      default-page-size: 200
  datasource:
    url: jdbc:postgresql://localhost:5432/sprout
    username: sprout
    password: sprout
    driver-class-name: org.postgresql.Driver


management:
  endpoints:
    web:
      exposure.include: "*"

logging:
  level:
    org.springframework.web: INFO

springdoc:
  api-docs:
    path: /v3/api-docs