/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.savantly.sprout.module.superset;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class SupersetModuleTest {
    @Test void testSomeLibraryMethod() {
        SupersetModule classUnderTest = new SupersetModule();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
