/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.savantly.sprout.module.superset;

import net.savantly.sprout.core.module.SproutWebModule;

public class SupersetModule implements SproutWebModule {
    private static final String ID = "superset";
	private static final String NAME = "Superset";
	private static final String VERSION = "2.0.0";

	public boolean someLibraryMethod() {
        return true;
    }

	@Override
	public String getDescription() {
		return "Superset charts in Sprout";
	}

	@Override
	public String getId() {
		return ID;
	}

	@Override
	public String getName() {
		return NAME;
	}

	@Override
	public String getVersion() {
		return VERSION;
	}
}
